### ISSUE TITLE
Error in pprey

### ISSUE THREAD

**Issue by hmorzaria** [Atlantis-Ecosystem-Model/ReactiveAtlantis#12]
During package installation I get the following error
unused argument (pprey = TRUE)

Then when using feeding.mat I get 

Error in text2num(prm, "pPREY", Vector = TRUE, pprey = TRUE) : 
  unused argument (pprey = TRUE)

**Comment by jporobicg** [comment]
Hi Hem,
I fixed the problem. the issue was caused because of the inner function text2num. This function is created in several main functions and in one of them, it was a missed argument (pprey=TRUE). Now is fixed so should be working. please let me know if that works.
Cheers
