### ISSUE TITLE
Error in recruitment.cal

### ISSUE THREAD

**Issue by jcaracappa1** [Atlantis-Ecosystem-Model/ReactiveAtlantis#31]
I was getting an error in recruitment.cal() with referencing column names in the group.file. I think it's caused by the column names being turned lowercase (Line 58) but being referenced with uppercase (Lines 90, 144, etc.).

**Comment by jporobicg** [comment]
Hi @jcaracappa1 , 
Sorry for that, I turned lowercase the column names to avoid problems related to different Atlantis versions but I missed changing some names to lowercase when I called some columns. Now it's fixed, let me know if this fixed the error for you.

**Comment by jcaracappa1** [comment]
Thanks for the quick fix. I think that there is one more uppercase on ln. 160 ( "groupType" -> "grouptype") that should fix it.

**Comment by jporobicg** [comment]
Hi, Fixed now. Thanks for looking at the problem.

Cheers

**Comment by jporobicg** [comment]
Bug fixed
