### ISSUE TITLE
Minor update seems to have created an error

### ISSUE THREAD

**Issue by raishalovindeer** [Atlantis-Ecosystem-Model/ReactiveAtlantis#45]
When running the updated ReactiveAtlantis in R-Studio, the following error results:

`Error in data.frame(Time = Time, FG = paste0(as.character(age.grp$longname[age]),  : 
  arguments imply differing number of rows: 154, 1, 123`

**Comment by jporobicg** [comment]
Nice Catch!. I updated the 'compare()' function. The problem was using the time (date) vector, which needs to be different when you have run with a different time frame.

**Comment by raishalovindeer** [comment]
Hmm. I updated the files, but I still get that same error message, exactly as it's copied above.

**Comment by jporobicg** [comment]
It should be fixed now. let me know how it goes

**Comment by raishalovindeer** [comment]
Fixed and looking great! Thanks Javier.
