### ISSUE TITLE
function description needs updating? 

### ISSUE THREAD

**Issue by hollyannperryman** [Atlantis-Ecosystem-Model/ReactiveAtlantis#57]
I was double checking how to use the predation() function on the github (https://github.com/Atlantis-Ecosystem-Model/ReactiveAtlantis), and the page says to do the following if you do not have the agebiomindx.txt file:

predation(biom, grp.csv, diet.file, bio.age = NULL)

but this did not work until I tried  

predation(biom, grp.csv, diet.file, age.biomass = NULL)

Did the bio.age input get replaced by age.biomass? If so maybe the main github needs updating? Thanks!

**Comment by jporobicg** [comment]
Thanks, @hollyannperryman GitHub page is updated!
