### ISSUE TITLE
Found a bug with feeding.mat() - quick fix

### ISSUE THREAD

**Issue by hollyannperryman** [Atlantis-Ecosystem-Model/ReactiveAtlantis#58]
Hei Javier! I was trying to get feeding.mat() to work with the GoM files and I kept getting an error about a variable not being found. I did some digging into the script and I found that the error was happening within the Bio.func() function and a mismatch with the groups.csv column headers. If you go into the feeding.mat() function, line 101 and 102, there is a safety net to fix the headers in the groups.csv file, but in the GOM model we use "inverttype" as the column head - note "invertype". I switched the code to this: 

  if(any(grepl('inverttype', names(groups.csv)))){
    names(groups.csv)[which(grepl('inverttype', names(groups.csv)))] <- 'grouptype'
  }

and I was able to get it to run. :)

**Comment by jporobicg** [comment]
Hi, @hollyannperryman I added the line to the function. it should be working now. There is the option to have invertype and inverttype as headers.
