### ISSUE TITLE
help with error messages running feeding.mat and growth.pp

### ISSUE THREAD

**Issue by yingmzhao** [Atlantis-Ecosystem-Model/ReactiveAtlantis#59]
Javier, 
I got the following error messages when running feeding.mat

Error in data.frame(FG = min.depth[, 1], Min = min.depth[, 2], Max = max.depth[which(max.depth[,  : 
  arguments imply differing number of rows: 53, 52

and error message when running growth.pp
Error in if (flaghabd == 1) { : the condition has length > 1.

Could you or anyone else in the group help me with the solutions, please?

**Comment by jporobicg** [comment]
Hi, 
It looks like both issues can be associated with duplicated parameters in Atlantis. Try running the Atlantis with check_dups 1 (in the run prm file) . Atlantis should tell you what parameters are duplicated.

**Comment by yingmzhao** [comment]
Thanks for the response. I removed 3 duplicated parameters in the bio parameter file and now the feeding.mat works fine. but i am still having the same error message for growth.pp.  Any suggestions?

**Comment by jporobicg** [comment]
Hi,
Can you run the function in debugger mode? add the following line before running the function
`debug(growth.pp)`
Then print out flaghabd in line 100

**Comment by yingmzhao** [comment]
Here are from the debug mode and print out flaghabd

Browse[2]> flaghabd
             FG Value
1 flaghabdepend     0
Browse[2]> 


Browse[2]> print(flaghabd)
             FG Value
1 flaghabdepend     0
Browse[2]>

**Comment by jporobicg** [comment]
I fixed the issue. The problem was the reading of flaghabd. It was using the old approach.
Do an update of the code and it should work

**Comment by yingmzhao** [comment]
Excellent!  It works now and I can see the interactive windows and plots for most plots. Under the page tag "Growth curves Zoo and PPs", for a few dynamic boxes, there is no plot but an error message "Error: 'names' attribute [5] must be the same length as the vector [4]". The other boxes seem to work fine. Any thoughts?

**Comment by jporobicg** [comment]
I will say try to debug the code again and check where it is failing. Probably there is something related to the prm file. Can you share the files you are using?
