### ISSUE TITLE
Recruitment.cal

### ISSUE THREAD

**Issue by yingmzhao** [Atlantis-Ecosystem-Model/ReactiveAtlantis#61]
Javier, The recruitment.cal produced an error message: 

Error: dims [product 1] do not match the length of object [11]

After entering the debugging mode, I found that the line 38 is to read.csv (YOY.txt file), but the file is a YOY.txt file. I tried to change to read.delim(), but could not make it work. Could you please to help fixing the code? thanks

**Comment by jporobicg** [comment]
G'day,
Using the read.csv is faster than using the read.table. which is why I'm using it. The problem is something else, probably related to the size of the arrays. Can you share the files you are using to run this tool with me?

Cheers

**Comment by yingmzhao** [comment]
Thanks for your reply. I will share with you the following five files: init.nc, output.nc, bio.prm, grp.csv, YOY.txt using a google drive to reproduce the error message for recruitment.cal.  Please let me know if you need any other files. Looking forward to your updates.

**Comment by jporobicg** [comment]
G'day, The problem was how I dealt with the vectorization of the names. Apparently, that way of indexing is no longer available in the new versions of R. That is fixed now.

I also added the option to work with the Ricker function
Now, there is an issue with one of your Beta parameters. You forgot to add the E in Rbeta_LWF.

**Comment by yingmzhao** [comment]
Javier, 
Great job! Now the code is working for me now. I have tested all the codes except for catch calculation that will be tested in near future. So far all the codes work perfectly and are very handy to plot the results. You have done a great job to help with creating the meaningful plots. I greatly appreciate your work!

My only wish now is: Could you please provide a document (like a science manual) explaining how the output data organized in each file and how to create these plots using the output data, which helps users to interpolate the plots and output them as publishable tables and figures.
